# difference.py
#
# A script to plot the difference between two hyperspectral spectra
# from specified .csv files.
#
# The expected file format is the same as that generated by picker.py
# --- one row giving the band wavelengths, followed by one or more
# rows giving the reflectance at the wavelength of that column.
#
# Spectra extracted from some gain-adjusted images will not have
# proper wavelngths, but instead proxies which just count rows, so it
# is not advised to use difference on a combination of adjusted and
# not-adjusted files.
#
# Simon Parsons
# September 2025
#
# Borrowing from:
# https://www.spectralpython.net
# https://www.geeksforgeeks.org/working-images-python/
# https://www.geeksforgeeks.org/command-line-arguments-in-python/

import sys
import getopt
import spectral as sp
import utils

#
# Print help message.
#
def displayHelp():
    print("difference.py expects to be run in the following modes:")
    print("1) python difference.py -h or difference plotter.py --Help, which displays this message;")
    print("2) python difference.py -i1 <filename1> -i2 <filename2>, or python plotter.py -Input1 <filename1> -Input <filename2> which displays the difference between the two waveforms")
    print("<filename-n> should be a csv file holding waveforms.")

#
# Just reads commandline arguments. All the work is done by functions
# in utils.py
#
def main():
    help = False
    file1 = False
    file2 = False
    
    # Drop the filename from the list of command line arguments
    argList = sys.argv[1:]

    # I'm sure there is a better way of handling the two file
    # arguments, but this should work.
    
    # We support help, printing all spectra, or computing and printing
    # the pointwise average of the spectra
    options = "hi:j:"

    # Long options
    long_options = ["Help", "Input1=", "Input2="]

    try:
        # Parsing argument
        arguments, values = getopt.getopt(argList, options, long_options)
    
        # checking each argument
        for currentArgument, currentValue in arguments:
            if currentArgument in ("-h", "--Help"):
                displayHelp()
                help = True
            
            elif currentArgument in ("-i", "--Input1"):
                bands1, intensities1 = utils.openWavebandFile(currentValue)
                file1 = True
                
            elif currentArgument in ("-j", "--Input2"):
                bands2, intensities2 = utils.openWavebandFile(currentValue)
                file2 = True
                
    except getopt.error as err:
        # output error, and return with an error code
        print (str(err))

    if not help:
        if file1 and file2:
            utils.plotDifference(bands1, bands2, intensities1, intensities2)
        else:
            print("Need two files to be specified")

if __name__ == "__main__":
    main()
